### ISSUE TITLE
Cannot display article title in global list view

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-app#196]
URL: https://bchai.cc/2010/06/26/%E9%9D%96%E4%B9%8B%E8%88%87%E5%8F%AF%E6%BE%84/

![IMG_1061](https://user-images.githubusercontent.com/17264698/89876688-93b5fc00-dbf1-11ea-9f46-239345751cf6.jpg)

**Comment by nwingt** [comment]
Seems related to #178, closing this.
