### ISSUE TITLE
Error occur when signing in with Authcore

### ISSUE THREAD

**Issue by edmondyu** [likecoin/likecoin-app#23]
Nokia 7.1
Android v9

The error pops up right after pressing the sign in button.

![WhatsApp Image 2019-11-29 at 8 54 27 PM](https://user-images.githubusercontent.com/17264698/69870360-9cc49e80-12ea-11ea-93e5-6fed30267f5f.jpeg)

**Comment by phoebepoon** [comment]
Connect to Google social sign-in on web. But cannot sign in with Google on apps. 
<img width="1246" alt="Screenshot 2019-11-30 at 4 30 42 PM" src="https://user-images.githubusercontent.com/58356976/69898091-6e4ccf00-138f-11ea-90b8-02ea67983a62.png">
![Screenshot_20191130-163114](https://user-images.githubusercontent.com/58356976/69898094-77d63700-138f-11ea-8cff-017a2fc599aa.jpg)
![Screenshot_20191130-163122](https://user-images.githubusercontent.com/58356976/69898096-7ad12780-138f-11ea-9fea-1698b7924bd1.jpg)

**Comment by williamchong007** [comment]
@edmondyu issue was due to old version of android app (you need to beta one 0.11.2)
@phoebepoon issue was due to the fact that the app is still pointing to testnet, mainnet binding relation is not yet imported
close for now unless this still occur after we go production on mainnet
