### ISSUE TITLE
Error 403 occur when trying to press Like button in one of the articles (iOS & Andriod)

### ISSUE THREAD

**Issue by phoebepoon** [likecoin/likecoin-app#24]
![Image from iOS (2)](https://user-images.githubusercontent.com/58356976/69898198-ca642300-1390-11ea-9086-26ca40b08a41.png)
![Image from iOS (1)](https://user-images.githubusercontent.com/58356976/69898200-ccc67d00-1390-11ea-970b-525a34000256.png)
![Screenshot_20191130-164551](https://user-images.githubusercontent.com/58356976/69898217-ff707580-1390-11ea-98b3-290cffa79a21.jpg)

**Comment by williamchong007** [comment]
known issue in rinkeby/taipei, please retest on monday after we switch to mainnet/sheungwan
close for now
