### ISSUE TITLE
Number of like clap shown in app is different from button list, which is different from matters

### ISSUE THREAD

**Issue by williamchong** [likecoin/likecoin-app#242]
e.g. In matters, 255 like from 52 user
https://matters.news/@abundantlife/%E9%A6%AC%E7%89%B9%E5%B8%82%E5%B9%B4%E5%BA%A6%E5%AD%97-%E8%AE%9A-bafyreie6xe427eigxuef3t3gk7hu6q35oufd7c5o46slwpjv4uvlbr5foi
In button ui, 250 like from 51 user
https://button.like.co/in/embed/abundance/list?referrer=https%3A%2F%2Fmatters.news%2F%40abundantlife%2F%25E9%25A6%25AC%25E7%2589%25B9%25E5%25B8%2582%25E5%25B9%25B4%25E5%25BA%25A6%25E5%25AD%2597-%25E8%25AE%259A-bafyreie6xe427eigxuef3t3gk7hu6q35oufd7c5o46slwpjv4uvlbr5foi
However user report that he is seeing a count of 173+22+0 =195
https://matters.news/@abundantlife/%E6%AF%8F%E7%AF%87%E6%96%87%E7%AB%A0liker-app%E7%9A%84%E6%8B%8D%E6%89%8B%E6%95%B8%E6%AF%94matters%E5%B0%91%E4%BA%8650%E5%80%8B%E6%8B%8D%E6%89%8B%E6%95%B8-bafyreia2yc5mnbult6sk7hksunqrcllrzec5jsqzjmk3xhq5uxr3kjf4s4

Something is either wrong with app pagination or api pagination

**Comment by DayDreamer11** [comment]
I hope that I can recount my like after the bug fixed

**Comment by williamchong** [comment]
Should be solved after fixing a bug in log data API count
